import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Barre laterale du site de documentation (DOC-01).
 *
 * ECRITE A LA MAIN, ET C'EST LE TICKET QUI L'EXIGE. Docusaurus sait deduire une
 * barre de l'arborescence des fichiers (`type: 'autogenerated'`) : elle suit
 * alors l'ordre alphabetique des dossiers, corrige a coups de `_category_.json`
 * et de `sidebar_position` semes dans chaque fichier. Ici l'ordre est un choix
 * de LECTURE -- on decouvre le projet, puis son architecture, puis chaque
 * couche, et les decisions ferment la marche -- et il se lit en entier dans ce
 * fichier.
 *
 * Les libelles sont portes ici plutot qu'en `sidebar_label` dans chaque page,
 * pour la meme raison : une seule source de verite, et l'ordre de lecture se
 * relit d'un coup d'oeil.
 *
 * UNE ENTREE PLATE PAR SECTION tant qu'une section n'a qu'une page ; des
 * qu'elle en gagne une seconde, l'entree devient une `category` dont le `link`
 * reste la page d'index. TOUTES les sections suivent desormais cette forme :
 * Architecture etait la derniere a n'avoir qu'une page, et DOC-02a lui en a
 * donne quatre. Une categorie livree vide afficherait une section qui ne se
 * deplie pas -- c'est la raison de la regle, et elle n'a plus d'exception.
 *
 * Les libelles des items d'une categorie restent courts : le numero et le
 * titre complet d'un ADR vivent dans la page, l'ordre du registre suffit ici.
 */
const sidebars: SidebarsConfig = {
  documentation: [
    {
      type: 'category',
      label: 'Démarrer',
      link: { type: 'doc', id: 'getting-started/index' },
      items: [
        { type: 'doc', id: 'getting-started/installation', label: 'Installation' },
        { type: 'doc', id: 'getting-started/demarrage', label: 'Démarrage' },
        {
          type: 'doc',
          id: 'getting-started/conventions-du-depot',
          label: 'Conventions du dépôt',
        },
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      link: { type: 'doc', id: 'architecture/index' },
      items: [
        { type: 'doc', id: 'architecture/glossaire', label: 'Vocabulaire' },
        {
          type: 'doc',
          id: 'architecture/ecrire-un-module-conforme',
          label: 'Écrire un module',
        },
        { type: 'doc', id: 'architecture/anti-patterns', label: 'Interdits' },
        { type: 'doc', id: 'architecture/carte-de-contexte', label: 'Carte de contexte' },
      ],
    },
    {
      type: 'category',
      label: 'Backend',
      link: { type: 'doc', id: 'backend/index' },
      items: [
        { type: 'doc', id: 'backend/structure', label: 'Structure' },
        {
          type: 'doc',
          id: 'backend/architecture-du-service',
          label: 'Architecture du service',
        },
        { type: 'doc', id: 'backend/configuration', label: 'Configuration' },
        { type: 'doc', id: 'backend/persistance', label: 'Persistance' },
        { type: 'doc', id: 'backend/unite-de-travail', label: 'Unité de travail' },
        {
          type: 'doc',
          id: 'backend/doublures-en-memoire',
          label: 'Doublures en mémoire',
        },
        { type: 'doc', id: 'backend/migrations', label: 'Migrations' },
        { type: 'doc', id: 'backend/cache', label: 'Cache' },
        { type: 'doc', id: 'backend/stockage-objet', label: 'Stockage objet' },
        { type: 'doc', id: 'backend/taches-de-fond', label: 'Tâches de fond' },
        {
          type: 'doc',
          id: 'backend/verification-email-otp',
          label: 'Vérification d’adresse (OTP)',
        },
        { type: 'doc', id: 'backend/notifications', label: 'Notifications' },
        { type: 'doc', id: 'backend/jetons', label: 'Jetons' },
        { type: 'doc', id: 'backend/mots-de-passe', label: 'Mots de passe' },
        { type: 'doc', id: 'backend/surface-http', label: 'Surface HTTP' },
        { type: 'doc', id: 'backend/erreurs', label: 'Erreurs' },
        { type: 'doc', id: 'backend/journalisation', label: 'Journalisation' },
        { type: 'doc', id: 'backend/dependances', label: 'Dépendances' },
        { type: 'doc', id: 'backend/qualite-et-typage', label: 'Qualité et typage' },
      ],
    },
    {
      type: 'category',
      label: 'Frontend',
      link: { type: 'doc', id: 'frontend/index' },
      items: [
        {
          type: 'doc',
          id: 'frontend/configurations-partagees',
          label: 'Configurations partagées',
        },
        { type: 'doc', id: 'frontend/bibliotheque-ui', label: 'Bibliothèque @repo/ui' },
        { type: 'doc', id: 'frontend/client-api-genere', label: 'Client d’API généré' },
        { type: 'doc', id: 'frontend/les-trois-applications', label: 'Les trois applications' },
      ],
    },
    {
      type: 'category',
      label: 'Infrastructure',
      link: { type: 'doc', id: 'infrastructure/index' },
      items: [
        { type: 'doc', id: 'infrastructure/ports-et-services', label: 'Ports et URLs' },
        { type: 'doc', id: 'infrastructure/image-api', label: 'Image de l’API' },
        { type: 'doc', id: 'infrastructure/image-frontends', label: 'Image des frontends' },
        { type: 'doc', id: 'infrastructure/mode-developpement', label: 'Mode développement' },
        { type: 'doc', id: 'infrastructure/minio', label: 'MinIO' },
        { type: 'doc', id: 'infrastructure/mailpit', label: 'Mailpit' },
        {
          type: 'doc',
          id: 'infrastructure/site-de-documentation',
          label: 'Site de documentation',
        },
        { type: 'doc', id: 'infrastructure/makefile-et-scripts', label: 'Makefile et scripts' },
      ],
    },
    {
      type: 'category',
      label: 'Décisions (ADR)',
      link: { type: 'doc', id: 'adr/index' },
      items: [
        { type: 'doc', id: 'adr/0001-monorepo', label: 'Monorepo' },
        { type: 'doc', id: 'adr/0002-uv-outillage-python', label: 'Outillage Python (uv)' },
        { type: 'doc', id: 'adr/0003-monolithe-modulaire', label: 'Monolithe modulaire' },
        { type: 'doc', id: 'adr/0004-tenance-par-groupe', label: 'Tenance par groupe' },
        { type: 'doc', id: 'adr/0005-appartenance-datee', label: 'Appartenance datée' },
        { type: 'doc', id: 'adr/0006-dossier-medical-animal', label: 'Dossier de l’animal' },
        {
          type: 'doc',
          id: 'adr/0007-client-api-genere-orval',
          label: 'Client d’API généré (Orval)',
        },
        { type: 'doc', id: 'adr/0008-taskiq-taches-de-fond', label: 'Tâches de fond (TaskIQ)' },
        {
          type: 'doc',
          id: 'adr/0009-unite-de-travail-par-module',
          label: 'Unité de travail par module',
        },
        { type: 'doc', id: 'adr/0010-migrations-alembic', label: 'Migrations (Alembic)' },
        {
          type: 'doc',
          id: 'adr/0011-routage-versionne-par-module',
          label: 'Routage par module (/api/v1)',
        },
        { type: 'doc', id: 'adr/0012-perimetre-de-requete', label: 'Périmètre de requête' },
        {
          type: 'doc',
          id: 'adr/0013-filtre-de-tenance-dans-le-depot',
          label: 'Filtre de tenance',
        },
        {
          type: 'doc',
          id: 'adr/0014-traduction-des-erreurs-a-la-bordure',
          label: 'Erreurs à la bordure',
        },
        {
          type: 'doc',
          id: 'adr/0015-cles-etrangeres-frontiere-module',
          label: 'Clés étrangères au bord du module',
        },
        {
          type: 'doc',
          id: 'adr/0016-unicite-email-insensible-casse',
          label: 'Unicité d’e-mail',
        },
        { type: 'doc', id: 'adr/0017-pagination-par-offset', label: 'Pagination' },
        {
          type: 'doc',
          id: 'adr/0018-journalisation-bibliotheque-standard',
          label: 'Journaux structurés',
        },
        { type: 'doc', id: 'adr/0019-contrat-openapi-exporte', label: 'Contrat OpenAPI exporté' },
        { type: 'doc', id: 'adr/0020-otp-hache-et-echec-ferme', label: 'OTP haché' },
        {
          type: 'doc',
          id: 'adr/0021-notification-par-evenement',
          label: 'Notification par événement',
        },
        {
          type: 'doc',
          id: 'adr/0022-transport-email-partage',
          label: 'Transport e-mail partagé',
        },
        {
          type: 'doc',
          id: 'adr/0023-doublures-en-memoire-et-conformite',
          label: 'Conformité des doublures',
        },
        {
          type: 'doc',
          id: 'adr/0024-jetons-audience-par-application',
          label: 'Audience par application',
        },
        {
          type: 'doc',
          id: 'adr/0025-politique-de-mot-de-passe-et-degradation-hibp',
          label: 'Politique de mot de passe',
        },
        {
          type: 'doc',
          id: 'adr/0026-fiche-technique-praticien',
          label: 'Fiche technique du praticien',
        },
      ],
    },
    {
      type: 'category',
      label: 'Écarts assumés',
      link: { type: 'doc', id: 'ecarts/index' },
      items: [
        { type: 'doc', id: 'ecarts/setup', label: 'SETUP' },
        { type: 'doc', id: 'ecarts/infra', label: 'INFRA' },
        { type: 'doc', id: 'ecarts/back', label: 'BACK' },
        { type: 'doc', id: 'ecarts/shared', label: 'SHARED' },
        { type: 'doc', id: 'ecarts/front', label: 'FRONT' },
        { type: 'doc', id: 'ecarts/doc', label: 'DOC' },
      ],
    },
  ],
};

export default sidebars;
