import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Barre laterale du site de documentation (DOC-01).
 *
 * ECRITE A LA MAIN, ET C'EST LE TICKET QUI L'EXIGE. Docusaurus sait deduire une
 * barre de l'arborescence des fichiers (`type: 'autogenerated'`) : elle suit
 * alors l'ordre alphabetique des dossiers, corrige a coups de `_category_.json`
 * et de `sidebar_position` semes dans chaque fichier. Ici l'ordre est un choix
 * de LECTURE -- on decouvre le projet, puis son architecture, puis chaque
 * couche, et les decisions ferment la marche -- et il se lit en entier dans ce
 * fichier.
 *
 * Les libelles sont portes ici plutot qu'en `sidebar_label` dans chaque page,
 * pour la meme raison : une seule source de verite, et l'ordre de lecture se
 * relit d'un coup d'oeil.
 *
 * UNE ENTREE PLATE PAR SECTION tant qu'une section n'a qu'une page ; des
 * qu'elle en gagne une seconde, l'entree devient une `category` dont le `link`
 * reste la page d'index. Les ADR (DOC-02b) suivent cette forme ci-dessous ;
 * Architecture (DOC-02a) et les pages de DOC-02c l'adopteront a leur tour --
 * une categorie livree vide afficherait une section qui ne se deplie pas.
 *
 * Les libelles des items d'une categorie restent courts : le numero et le
 * titre complet d'un ADR vivent dans la page, l'ordre du registre suffit ici.
 */
const sidebars: SidebarsConfig = {
  documentation: [
    { type: 'doc', id: 'getting-started/index', label: 'Démarrer' },
    { type: 'doc', id: 'architecture/index', label: 'Architecture' },
    { type: 'doc', id: 'backend/index', label: 'Backend' },
    { type: 'doc', id: 'frontend/index', label: 'Frontend' },
    { type: 'doc', id: 'infrastructure/index', label: 'Infrastructure' },
    {
      type: 'category',
      label: 'Décisions (ADR)',
      link: { type: 'doc', id: 'adr/index' },
      items: [
        { type: 'doc', id: 'adr/0001-monorepo', label: 'Monorepo' },
        { type: 'doc', id: 'adr/0002-uv-outillage-python', label: 'Outillage Python (uv)' },
        { type: 'doc', id: 'adr/0003-monolithe-modulaire', label: 'Monolithe modulaire' },
        { type: 'doc', id: 'adr/0004-tenance-par-groupe', label: 'Tenance par groupe' },
        { type: 'doc', id: 'adr/0005-appartenance-datee', label: 'Appartenance datée' },
        { type: 'doc', id: 'adr/0006-dossier-medical-animal', label: 'Dossier de l’animal' },
        {
          type: 'doc',
          id: 'adr/0007-client-api-genere-orval',
          label: 'Client d’API généré (Orval)',
        },
        { type: 'doc', id: 'adr/0008-taskiq-taches-de-fond', label: 'Tâches de fond (TaskIQ)' },
      ],
    },
  ],
};

export default sidebars;
