import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Barre laterale du site de documentation (DOC-01).
 *
 * ECRITE A LA MAIN, ET C'EST LE TICKET QUI L'EXIGE. Docusaurus sait deduire une
 * barre de l'arborescence des fichiers (`type: 'autogenerated'`) : elle suit
 * alors l'ordre alphabetique des dossiers, corrige a coups de `_category_.json`
 * et de `sidebar_position` semes dans chaque fichier. Ici l'ordre est un choix
 * de LECTURE -- on decouvre le projet, puis son architecture, puis chaque
 * couche, et les decisions ferment la marche -- et il se lit en entier dans ce
 * fichier.
 *
 * Les libelles sont portes ici plutot qu'en `sidebar_label` dans chaque page,
 * pour la meme raison : une seule source de verite, et l'ordre de lecture se
 * relit d'un coup d'oeil.
 *
 * UNE ENTREE PLATE PAR SECTION tant qu'une section n'a qu'une page. Des que
 * DOC-02a, DOC-02b ou DOC-02c en ajoutent une seconde, l'entree concernee
 * devient une `category` dont le `link` reste la page d'index actuelle :
 *
 *   { type: 'category', label: 'Architecture', link: { type: 'doc', id: 'architecture/index' },
 *     items: ['architecture/modeles', 'architecture/carte-de-contexte'] }
 *
 * Une categorie livree vide des maintenant afficherait six sections qui ne se
 * deplient pas.
 */
const sidebars: SidebarsConfig = {
  documentation: [
    { type: 'doc', id: 'getting-started/index', label: 'Démarrer' },
    { type: 'doc', id: 'architecture/index', label: 'Architecture' },
    { type: 'doc', id: 'backend/index', label: 'Backend' },
    { type: 'doc', id: 'frontend/index', label: 'Frontend' },
    { type: 'doc', id: 'infrastructure/index', label: 'Infrastructure' },
    { type: 'doc', id: 'adr/index', label: 'Décisions (ADR)' },
  ],
};

export default sidebars;
